# Generated by Django 5.0.6 on 2024-07-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='runtime_minutes',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
